# Generated by Django 3.1.1 on 2020-09-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_task_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_date',
        ),
    ]
